
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Intitek.Welcome.Domain
{
    using Intitek.Welcome.Infrastructure.Domain;
    using System;
    using System.Collections.Generic;
    
public partial class BackUpIntitek : EntityBase<int>, IAggregateRoot
{
    protected override void Validate()
    {
            throw new NotImplementedException();
    }
    public string UserName { get; set; }

    public string Email { get; set; }

    public int ID { get; set; }

    public int ID_AD { get; set; }

    public Nullable<int> ID_Document { get; set; }

    public Nullable<System.DateTime> IsRead { get; set; }

    public Nullable<System.DateTime> IsTested { get; set; }

    public Nullable<System.DateTime> IsApproved { get; set; }

}

}
