//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intitek.Welcome.Domain
{
    using Intitek.Welcome.Infrastructure.Domain;
    using System;
    using System.Collections.Generic;

    public partial class Config : EntityBase<string>, IAggregateRoot
    {
        protected override void Validate()
        {
            throw new NotImplementedException();
        }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Config()
        {
        }
        public Config(string id)
        {
            base.Id = id;

        }

        public string Id { get; set; }
        public string Value { get; set; }
    }
}
