//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intitek.Welcome.Domain
{
    using Intitek.Welcome.Infrastructure.Domain;
    using System;
    using System.Collections.Generic;

    public partial class DocumentVersionLang : EntityBase<long>, IAggregateRoot
    {
        protected override void Validate()
        {
            throw new NotImplementedException();
        }

        public long ID_DocumentVersion { get; set; }
        public int ID_Lang { get; set; }
        public string Name { get; set; }
        public string NomOrigineFichier { get; set; }
        public byte[] Data { get; set; }

        public virtual DocumentVersion DocumentVersion { get; set; }
        public virtual Lang Lang { get; set; }
    }
}
