
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Intitek.Welcome.Domain
{
    using Intitek.Welcome.Infrastructure.Domain;
    using System;
    using System.Collections.Generic;
    
public partial class Document : EntityBase<int>, IAggregateRoot
    {
        protected override void Validate()
        {
            throw new NotImplementedException();
        }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Document()
    {

        this.EntityDocument = new HashSet<EntityDocument>();

        this.ProfileDocument = new HashSet<ProfileDocument>();

        this.DocumentLang = new HashSet<DocumentLang>();

        this.UserDocument = new HashSet<UserDocument>();

        this.DocumentVersion = new HashSet<DocumentVersion>();

        this.HistoUserQcmDocVersion = new HashSet<HistoUserQcmDocVersion>();

        this.UserQcm = new HashSet<UserQcm>();

    }


    public int ID { get; set; }

    public string Version { get; set; }

    public Nullable<System.DateTime> Date { get; set; }

    public Nullable<int> Approbation { get; set; }

    public Nullable<int> Test { get; set; }

    public string Commentaire { get; set; }

    public string ContentType { get; set; }

    public string Extension { get; set; }

    public Nullable<bool> Inactif { get; set; }

    public string TypeAffectation { get; set; }

    public Nullable<int> IdQcm { get; set; }

    public Nullable<int> ID_Category { get; set; }

    public bool isMajor { get; set; }

    public bool IsNoActionRequired { get; set; }

    public Nullable<int> ID_UserCre { get; set; }

    public Nullable<int> ID_UserUpd { get; set; }

    public Nullable<int> ID_UserDel { get; set; }

    public Nullable<System.DateTime> DateCre { get; set; }

    public Nullable<System.DateTime> DateUpd { get; set; }

    public Nullable<System.DateTime> DateDel { get; set; }

    public bool ReadBrowser { get; set; }

    public bool ReadDownload { get; set; }

    public bool PhaseEmployee { get; set; }

    public bool PhaseOnboarding { get; set; }

    public bool isMetier { get; set; }

    public bool isStructure { get; set; }

    public Nullable<int> ID_SubCategory { get; set; }

    public bool isMagazine { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EntityDocument> EntityDocument { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ProfileDocument> ProfileDocument { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DocumentLang> DocumentLang { get; set; }

    public virtual SubCategory SubCategory { get; set; }

    public virtual DocumentCategory DocumentCategory { get; set; }

    public virtual Qcm Qcm { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserDocument> UserDocument { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DocumentVersion> DocumentVersion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<HistoUserQcmDocVersion> HistoUserQcmDocVersion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserQcm> UserQcm { get; set; }

    public virtual IntitekUser IntitekUser { get; set; }

    public virtual IntitekUser IntitekUser1 { get; set; }

    public virtual IntitekUser IntitekUser2 { get; set; }

}

}
