//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intitek.Welcome.Domain
{
    using Intitek.Welcome.Infrastructure.Domain;
    using System;
    using System.Collections.Generic;

    public partial class DocumentVersion : EntityBase<long>, IAggregateRoot
    {
        protected override void Validate()
        {
            throw new NotImplementedException();
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentVersion()
        {
            this.DocumentVersionLang = new List<DocumentVersionLang>();
        }

        public long ID { get; set; }
        public int ID_Document { get; set; }
        public int ID_UserCre { get; set; }
        public bool IsMajor { get; set; }
        public System.DateTime DateCre { get; set; }
        public string ContentType { get; set; }
        public string Extension { get; set; }
        public string Version { get; set; }

        public virtual Document Document { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentVersionLang> DocumentVersionLang { get; set; }
    }
}
