//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intitek.Welcome.Domain
{
    using Intitek.Welcome.Infrastructure.Domain;
    using System;
    using System.Collections.Generic;

    public partial class HistoUserQcmDocVersion : EntityBase<long>, IAggregateRoot
    {
        protected override void Validate()
        {
            throw new NotImplementedException();
        }

        public long ID { get; set; }
        public int ID_IntitekUser { get; set; }
        public int ID_Qcm { get; set; }
        public int ID_Document { get; set; }
        public string Version { get; set; }
        public int Score { get; set; }
        public int ScoreMinimal { get; set; }
        public System.DateTime DateCre { get; set; }
        public System.DateTime DateFin { get; set; }

        public virtual Document Document { get; set; }
        public virtual Qcm Qcm { get; set; }
        public virtual IntitekUser IntitekUser { get; set; }
    }
}
