
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Intitek.Welcome.Domain
{
    using Intitek.Welcome.Infrastructure.Domain;
    using System;
    using System.Collections.Generic;
    
public partial class Histo_Document : EntityBase<int>, IAggregateRoot
    {
        protected override void Validate()
        {
            throw new NotImplementedException();
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Histo_Document()
    {

        this.Histo_DocumentLang = new HashSet<Histo_DocumentLang>();

        this.Histo_UserDocument = new HashSet<Histo_UserDocument>();

        this.Histo_DocumentVersion = new HashSet<Histo_DocumentVersion>();

        this.Histo_EntityDocument = new HashSet<Histo_EntityDocument>();

        this.Histo_ProfileDocument = new HashSet<Histo_ProfileDocument>();

        this.Histo_UserQcm = new HashSet<Histo_UserQcm>();

    }


    public string Mois { get; set; }

    public int ID { get; set; }

    public string Version { get; set; }

    public Nullable<System.DateTime> Date { get; set; }

    public Nullable<int> Approbation { get; set; }

    public Nullable<int> Test { get; set; }

    public string Commentaire { get; set; }

    public string ContentType { get; set; }

    public string Extension { get; set; }

    public Nullable<bool> Inactif { get; set; }

    public string TypeAffectation { get; set; }

    public Nullable<int> IdQcm { get; set; }

    public Nullable<int> ID_Category { get; set; }

    public bool isMajor { get; set; }

    public bool IsNoActionRequired { get; set; }

    public Nullable<int> ID_UserCre { get; set; }

    public Nullable<int> ID_UserUpd { get; set; }

    public Nullable<int> ID_UserDel { get; set; }

    public Nullable<System.DateTime> DateCre { get; set; }

    public Nullable<System.DateTime> DateUpd { get; set; }

    public Nullable<System.DateTime> DateDel { get; set; }

    public bool ReadBrowser { get; set; }

    public bool ReadDownload { get; set; }

    public bool PhaseEmployee { get; set; }

    public bool PhaseOnboarding { get; set; }

    public bool isMetier { get; set; }

    public bool isStructure { get; set; }

    public Nullable<int> ID_SubCategory { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Histo_DocumentLang> Histo_DocumentLang { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Histo_UserDocument> Histo_UserDocument { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Histo_DocumentVersion> Histo_DocumentVersion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Histo_EntityDocument> Histo_EntityDocument { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Histo_ProfileDocument> Histo_ProfileDocument { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Histo_UserQcm> Histo_UserQcm { get; set; }

    public virtual Histo_IntitekUser Histo_IntitekUser { get; set; }

}

}
