
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Intitek.Welcome.Domain
{
    using Intitek.Welcome.Infrastructure.Domain;
    using System;
    using System.Collections.Generic;
    
public partial class Histo_AD : EntityBase<int>, IAggregateRoot
    {
        protected override void Validate()
        {
            throw new NotImplementedException();
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Histo_AD()
    {

        this.Histo_IntitekUser = new HashSet<Histo_IntitekUser>();

    }


    public string Mois { get; set; }

    public int ID { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public string Domain { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public bool ToBeSynchronized { get; set; }

    public Nullable<System.DateTime> LastSynchronized { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Histo_IntitekUser> Histo_IntitekUser { get; set; }

}

}
