
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Intitek.Welcome.Domain
{
    using Intitek.Welcome.Infrastructure.Domain;
    using System;
    using System.Collections.Generic;
    
public partial class Histo_IntitekUser : EntityBase<int>, IAggregateRoot
    {
        protected override void Validate()
        {
            throw new NotImplementedException();
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Histo_IntitekUser()
    {

        this.Histo_Document = new HashSet<Histo_Document>();

        this.Histo_UserDocument = new HashSet<Histo_UserDocument>();

        this.Histo_ProfileUser = new HashSet<Histo_ProfileUser>();

        this.Histo_UserQcm = new HashSet<Histo_UserQcm>();

    }


    public string Mois { get; set; }

    public int ID { get; set; }

    public string Username { get; set; }

    public Nullable<int> Status { get; set; }

    public string EntityName { get; set; }

    public string AgencyName { get; set; }

    public bool isOnBoarding { get; set; }

    public string EmailOnBoarding { get; set; }

    public string PasswordOnBoarding { get; set; }

    public Nullable<System.DateTime> DateLastVisit { get; set; }

    public string Email { get; set; }

    public int ID_AD { get; set; }

    public string FullName { get; set; }

    public string FirstName { get; set; }

    public bool Active { get; set; }

    public string Type { get; set; }

    public Nullable<System.DateTime> InactivityStart { get; set; }

    public Nullable<System.DateTime> InactivityEnd { get; set; }

    public string InactivityReason { get; set; }

    public string Departement { get; set; }

    public string Division { get; set; }

    public Nullable<int> ID_Manager { get; set; }

    public string Pays { get; set; }

    public string Plaque { get; set; }

    public System.DateTime EntryDate { get; set; }

    public Nullable<System.DateTime> ExitDate { get; set; }



    public virtual Histo_AD Histo_AD { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Histo_Document> Histo_Document { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Histo_UserDocument> Histo_UserDocument { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Histo_ProfileUser> Histo_ProfileUser { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Histo_UserQcm> Histo_UserQcm { get; set; }

}

}
