
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Intitek.Welcome.Domain
{
    using Intitek.Welcome.Infrastructure.Domain;
    using System;
    using System.Collections.Generic;
    
public partial class HistoEmails : EntityBase<int>, IAggregateRoot
    {
        protected override void Validate()
        {
            throw new NotImplementedException();
        }

        public int ID { get; set; }

    public Nullable<int> Id_IntitekUser { get; set; }

    public Nullable<int> Id_MailTemplate { get; set; }

    public Nullable<System.DateTime> Date { get; set; }

    public string Message { get; set; }

    public Nullable<int> ID_Batch { get; set; }



    public virtual Batchs Batchs { get; set; }

    public virtual MailTemplate MailTemplate { get; set; }

    public virtual IntitekUser IntitekUser { get; set; }

}

}
