
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Intitek.Welcome.Domain
{
    using Intitek.Welcome.Infrastructure.Domain;
    using System;
    using System.Collections.Generic;
    
public partial class Histo_DocumentVersion : EntityBase<int>, IAggregateRoot
    {
        protected override void Validate()
        {
            throw new NotImplementedException();
        }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Histo_DocumentVersion()
    {

        this.Histo_DocumentVersionLang = new HashSet<Histo_DocumentVersionLang>();

    }


    public string Mois { get; set; }

    public long ID { get; set; }

    public int ID_Document { get; set; }

    public int ID_UserCre { get; set; }

    public bool IsMajor { get; set; }

    public System.DateTime DateCre { get; set; }

    public string ContentType { get; set; }

    public string Extension { get; set; }

    public string Version { get; set; }



    public virtual Histo_Document Histo_Document { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Histo_DocumentVersionLang> Histo_DocumentVersionLang { get; set; }

}

}
