
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Intitek.Welcome.Domain
{
    using Intitek.Welcome.Infrastructure.Domain;
    using System;
    using System.Collections.Generic;
    
public partial class ImportManager : EntityBase<int>, IAggregateRoot
    {
        protected override void Validate()
        {
            throw new NotImplementedException();
        }

        public string Nom { get; set; }

    public string Prenom { get; set; }

    public string Ville { get; set; }

    public string cn { get; set; }

    public string Manager_Nom { get; set; }

    public string Manager_Prenom { get; set; }

    public string Manager { get; set; }

    public string DOP { get; set; }

    public string Societe { get; set; }

    public string Categorie { get; set; }

    public string accountManager { get; set; }

    public string accountUser { get; set; }

    public string mailPerso { get; set; }

    public string accountManager_Astek_autre { get; set; }

}

}
