
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Intitek.Welcome.Domain
{
    using Intitek.Welcome.Infrastructure.Domain;
    using System;
    using System.Collections.Generic;
    
public partial class IntitekUser : EntityBase<int>, IAggregateRoot
    {
        protected override void Validate()
        {
            throw new NotImplementedException();
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public IntitekUser()
    {

        this.Document = new HashSet<Document>();

        this.Document1 = new HashSet<Document>();

        this.Document2 = new HashSet<Document>();

        this.HistoActions = new HashSet<HistoActions>();

        this.HistoEmails = new HashSet<HistoEmails>();

        this.HistoUserQcmDocVersion = new HashSet<HistoUserQcmDocVersion>();

        this.UserDocument = new HashSet<UserDocument>();

        this.ProfileUser = new HashSet<ProfileUser>();

        this.UserQcm = new HashSet<UserQcm>();

        this.IntitekUser1 = new HashSet<IntitekUser>();

    }


    public int ID { get; set; }

    public string Username { get; set; }

    public Nullable<int> Status { get; set; }

    public string EntityName { get; set; }

    public string AgencyName { get; set; }

    public bool isOnBoarding { get; set; }

    public string EmailOnBoarding { get; set; }

    public string PasswordOnBoarding { get; set; }

    public Nullable<System.DateTime> DateLastVisit { get; set; }

    public string Email { get; set; }

    public int ID_AD { get; set; }

    public string FullName { get; set; }

    public string FirstName { get; set; }

    public bool Active { get; set; }

    public string Type { get; set; }

    public Nullable<System.DateTime> InactivityStart { get; set; }

    public Nullable<System.DateTime> InactivityEnd { get; set; }

    public string InactivityReason { get; set; }

    public string Departement { get; set; }

    public string Division { get; set; }

    public Nullable<int> ID_Manager { get; set; }

    public string Pays { get; set; }

    public string Plaque { get; set; }

    public System.DateTime EntryDate { get; set; }

    public Nullable<System.DateTime> ExitDate { get; set; }

    public bool isReader { get; set; }



    public virtual AD AD { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Document> Document { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Document> Document1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Document> Document2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<HistoActions> HistoActions { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<HistoEmails> HistoEmails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<HistoUserQcmDocVersion> HistoUserQcmDocVersion { get; set; }

    public virtual StatusDefinition StatusDefinition { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserDocument> UserDocument { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ProfileUser> ProfileUser { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserQcm> UserQcm { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<IntitekUser> IntitekUser1 { get; set; }

    public virtual IntitekUser IntitekUser2 { get; set; }

}

}
