//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intitek.Welcome.Domain
{
    using Intitek.Welcome.Infrastructure.Domain;
    using System;
    using System.Collections.Generic;

    public partial class Qcm : EntityBase<int>, IAggregateRoot
    {
        protected override void Validate()
        {
            throw new NotImplementedException();
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Qcm()
        {
            this.Document = new List<Document>();
            this.HistoUserQcmDocVersion = new List<HistoUserQcmDocVersion>();
            this.UserQcm = new List<UserQcm>();
            this.Question = new List<Question>();
            this.QcmLang = new List<QcmLang>();
        }

        public Qcm(int id)
        {
            base.Id = id;
            this.Document = new List<Document>();
            this.HistoUserQcmDocVersion = new List<HistoUserQcmDocVersion>();
            this.UserQcm = new List<UserQcm>();
            this.Question = new List<Question>();
        }


        public int Id { get; set; }
        public System.DateTime DateCreation { get; set; }
        public Nullable<int> NoteMinimal { get; set; }
        public Nullable<int> Inactif { get; set; }
        public int NbQuestions { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Document { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoUserQcmDocVersion> HistoUserQcmDocVersion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QcmLang> QcmLang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserQcm> UserQcm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question> Question { get; set; }
    }
}
