//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intitek.Welcome.Domain
{
    using Intitek.Welcome.Infrastructure.Domain;
    using System;
    using System.Collections.Generic;

    public partial class Reponse : EntityBase<int>, IAggregateRoot
    {
        protected override void Validate()
        {
            throw new NotImplementedException();
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reponse()
        {
            this.ReponseLang = new List<ReponseLang>();
            this.UserQcmReponse = new List<UserQcmReponse>();
        }

        public Reponse(int id)
        {
            base.Id = id;
            this.ReponseLang = new List<ReponseLang>();
            this.UserQcmReponse = new List<UserQcmReponse>();
        }

        public int Id { get; set; }
        public int OrdreReponse { get; set; }
        public Nullable<bool> inactif { get; set; }
        public Nullable<int> ID_Question { get; set; }
        public bool IsRight { get; set; }

        public virtual Question Question { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReponseLang> ReponseLang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserQcmReponse> UserQcmReponse { get; set; }
    }
}
