//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intitek.Welcome.Domain
{
    using Intitek.Welcome.Infrastructure.Domain;
    using System;
    using System.Collections.Generic;

    public partial class UserQcmReponse : EntityBase<long>, IAggregateRoot
    {
        protected override void Validate()
        {
            throw new NotImplementedException();
        }

        public long ID { get; set; }
        public int ID_UserQcm { get; set; }
        public int ID_Reponse { get; set; }
        public System.DateTime DateCre { get; set; }

        public virtual Reponse Reponse { get; set; }
        public virtual UserQcm UserQcm { get; set; }
    }
}
